name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Release

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile && yarn build

      - name: Create Release
        if: success()  # Only create a release if the build succeeds
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0  # Specify the release tag
          release_name: Release v1.0.0
          body: Automated release for successful build
          draft: false
          prerelease: false
          files: ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}