name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Release

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile && yarn build
      # - name: Archive build results
      #   run: |
      #     tar -czvf build-results.tar.gz dist/**
      - name: Copy packaage.json file 
        run: cp package.json dist/

      - uses: actions/upload-artifact@v4
        with:
          name: build-results
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-results
          path: dist
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.1
          release_name: Release v1.0.1
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}