name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Release

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile && yarn build
      
      - name: Copy package.json files
        run: cp -r package.json dist/

      - name: Copy readme.md files
        run: cp -r README.md dist/

      - name: Publish new branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Switch to gh-pages branch
        run: |
          git checkout -b gh-pages

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          draft: false
          prerelease: false
          target_commitish: gh-pages
